### ISSUE TITLE
Multiple Calls to OpenAM Server for Cookie Name

### ISSUE THREAD

**Issue by ismail44** [jnsolutions/openam_auth#5]
It seems that the gem makes at least 4 calls to the server to fetch the cookie name for the OpenAM Token. Is there a reason that value isn't saved in an instance variable the first time the call is made?

**Comment by morhekil** [comment]
Hi,

yeah, looks like a bug, and an easy win to save a few requests. I pushed a fix for this, and I'll get it published to rubygems shortly.
